### ISSUE TITLE
restore workspaces where you left off

### ISSUE THREAD

**Issue by nikinbaidarr** [JonnyHaystack/i3-resurrect#102]
i3-resurrect is a great thing that really helps my productivity.
I save a workspace, and I can restore it with the programs and layouts when I want to.

However, I was wondering if there's a way to restore them programs where I left off, as in if I was in a terminal and editing a file in vim, then whenever I restore my workspace it restores that way (that file opened in vim) instead of just the terminal. 
Or, it restores the webpages i was browsing when it restores the browser?

Any insights will be highly appreciated.

**Comment by JonnyHaystack** [comment]
This is up to the programs you're using. It's impossible for i3-resurrect to save the state of an arbitrary application in a restorable way. If you launched the terminal from dmenu/rofi with something like `alacritty -e "vim file.txt" ` then it would restore correctly though. You can also use window command mappings in the config file and get creative. I recommend using i3-resurrect in conjunction with things like tmux + tmux-resurrect and set up your browser to automatically restore your session when you reopen it. Firefox and Chrome can both do this.
