### ISSUE TITLE
Feature request: avoid flicker when nothing is changed

### ISSUE THREAD

**Issue by QiangF** [JonnyHaystack/i3-resurrect#111]
Emacs has a nice feature called winner-mode (eyebrowse-mode is similar), winner-mode save emacs window layout automatically. I want to partly simulate winner-mode by saving workspace layout on leaving and restore it on entering, but for only a limited bindings, instead of a workspace switching hook, to make things easier.

The problem: i3-resurrect restore is not aware of the current layout, it should do a comparison and only restore when current layout is different from saved layout.

The minimum test config is:

    set $mod Mod4
    set $i3_resurrect i3-resurrect
    workspace_auto_back_and_forth yes
    bindsym $mod+Tab exec $i3_resurrect save; workspace back_and_forth; exec $i3_resurrect restore
    bindsym $mod+n exec $i3_resurrect save; workspace next; exec $i3_resurrect restore
    bindsym $mod+p exec $i3_resurrect save; workspace prev; exec $i3_resurrect restore
    bindsym $mod+1 exec $i3_resurrect save; workspace 1; exec $i3_resurrect restore
    bindsym $mod+2 exec $i3_resurrect save; workspace 2; exec $i3_resurrect restore
    bindsym $mod+3 exec $i3_resurrect save; workspace 3; exec $i3_resurrect restore
    bindsym $mod+4 exec $i3_resurrect save; workspace 4; exec $i3_resurrect restore
    bindsym $mod+5 exec $i3_resurrect save; workspace 5; exec $i3_resurrect restore
    bindsym $mod+6 exec $i3_resurrect save; workspace 6; exec $i3_resurrect restore
    bindsym $mod+7 exec $i3_resurrect save; workspace 7; exec $i3_resurrect restore
    bindsym $mod+8 exec $i3_resurrect save; workspace 8; exec $i3_resurrect restore
    bindsym $mod+9 exec $i3_resurrect save; workspace 9; exec $i3_resurrect restore

**Comment by QiangF** [comment]
The above doesn't seem to work. emacs can't appear on both workspace 2 and 3 before and after switching workspace.

**Comment by JonnyHaystack** [comment]
I'm not really understanding the problem. Could you take screenshots or a screen recording to demonstrate?

**Comment by QiangF** [comment]
Maybe a description is better than a screen cast.

1. I create layout 1, and put it on workspace 1, let assume it is a side by side hsplit layout, the two windows are Firefox and Emacs.
2. I switch to workspace 2, bring the Emacs window on workspace 1 there, and opens anoter Xterm window, also put the two side by side, thus create layout 2.
3. Now I switch back to workspace 1, I want the layout 1 back, ie. bring the Emacs window on workspace 2 to workspace 1, restore layout 1.
4. Now I switch back workspace 2, I want the layout 2 back, ie. bring the Emacs window on workspace 1 to workspace 2, resotre layout 2.

This is equivelant to use workspaces as layouts. And move windows automatically, just like winner-moder restoring previous layout with winner-undo. i3-resurrect seems unable to bring windows back from another workspace, I ended up with empty place holder and new window (like new Emacs) create with the following setting:

    set $mod Mod4
    # resurrect
    bindsym $mod+1 exec my-wb-switch.sh 1
    bindsym $mod+2 exec my-wb-switch.sh 2
    bindsym $mod+3 exec my-wb-switch.sh 3
    bindsym $mod+4 exec my-wb-switch.sh 4
    bindsym $mod+5 exec my-wb-switch.sh 5
    bindsym $mod+6 exec my-wb-switch.sh 6
    bindsym $mod+7 exec my-wb-switch.sh 7
    bindsym $mod+8 exec my-wb-switch.sh 8
    bindsym $mod+9 exec my-wb-switch.sh 9

In my-wb-switch.sh:

    #!/bin/sh
    i3-resurrect save
    sleep 0.2
    i3-msg -q "workspace $1"
    i3-resurrect restore

**Comment by JonnyHaystack** [comment]
So are you just trying to switch between different layouts quickly? Why not just save the workspace to a profile for each of your layouts and restore a profile with `--layout-only` when you want to switch layout?

**Comment by QiangF** [comment]
I think I give the wrong description. I will create a new issue.
