### ISSUE TITLE
Executing simultaneous restores of separate windows causes their contents to merge

### ISSUE THREAD

**Issue by KobeStaude** [JonnyHaystack/i3-resurrect#113]
By default, the user would use the "restore" mode to manually restore a workspace. In an attempt to have **several** workspaces be restored through a single keybinding, the contents of each workspace would be restored, but all in one workspace.

For example, my 1st workspace has a terminal, and my 2nd workspace has a browser. Executing restore for both workspaces on a single line in my i3 config would cause both the terminal and the browser to restore on the 1st workspace.

**To Reproduce**
Put the following in your i3 config, with workspaces one and two having been saved.
`bindsym $mod+p exec $i3_resurrect restore -w $ws1; exec $i3-resurrect restore -w $ws2`

**Expected behavior**
The contents of each workspace should be restored in their respective workspace.

**System information:**
 - Linux distribution: arch
 - i3-resurrect version: 1.4.5
 - i3 version: 4.21.1
 - Python version: 3.10.8

**Additional context**
I'm hoping this gets fixed so I can have my workspaces restore on login, which would be very cool.

**Comment by JonnyHaystack** [comment]
Restoring multiple workspaces at once is not supported due to limitations in i3. You can try adding a `sleep <n>` in between the commands to let it do one at a time. Maybe that will help you.
