### ISSUE TITLE
Add a way to configure swallow criteria per window class in the config file

### ISSUE THREAD

**Issue by JonnyHaystack** [JonnyHaystack/i3-resurrect#16]
The problem:

Sometimes a user may want to have different swallow criteria for different applications in the same workspace. Currently they would have to edit the file manually after each time they saved the workspace layout, which rather defeats the point of i3-resurrect.

Proposed solution:

Add a `window_swallow_criteria` option to the config file which can specify swallow criteria per window class. Here is an example:
```
  ...
  "window_swallow_criteria": {
    "Ario": ["class", "instance"]
  }
  ...
```

The config file should take priority over the `--swallow` option when deciding swallow criteria.

**Comment by josephoneill** [comment]
This is a wonderful idea, I am eagerly anticipating the implementation of this swallow feature with optional criteria. Thanks!

**Comment by JonnyHaystack** [comment]
Finished, coming out in next release (1.3.0)
