### ISSUE TITLE
invalid literal

### ISSUE THREAD

**Issue by NicholasFarrow** [JonnyHaystack/i3-resurrect#25]
Hi,

I can store and load layouts just find. However when trying to store programs I always get error like:
```
nick@nick:~/.i3/i3-resurrect$ i3-resurrect save -w 1 --programs-only
invalid literal for int() with base 10: '1:'
invalid literal for int() with base 10: '1:
```
And inside the `.json` only an empty list is saved `[]`.

Please let me know how I can alleviate this, or assist in debugging.
Thanks

**Comment by JonnyHaystack** [comment]
Hi, sorry I only just saw this. What's in your config file? It should be at `~/.config/i3-resurrect/config`

**Comment by JonnyHaystack** [comment]
Ok I'm pretty sure the error comes from [this line](https://github.com/JonnyHaystack/i3-resurrect/blob/master/i3_resurrect/util.py#L132) which means it's finding an invalid window ID for windows on your workspace. My first guess is that wmctrl just isn't installed. If it is, then something weird's going on with those windows and I'd need more information about what the windows are.

**Comment by NicholasFarrow** [comment]
Thanks so much! I was certain I installed wmctrl, but turns out it was missing.
