### ISSUE TITLE
Windows loading with ?

### ISSUE THREAD

**Issue by sabrehagen** [JonnyHaystack/i3-resurrect#66]
On the latest release, when reloading the following is observed:

![image](https://user-images.githubusercontent.com/1094600/69049828-dd9ff600-0a54-11ea-89ea-22b142f3639c.png)

![image](https://user-images.githubusercontent.com/1094600/69049464-04a9f800-0a54-11ea-8ea5-68c9412736f1.png)

The expected layout is a 50/50 split with terminal and browser with no gap in between.

[Workspace 1 Layout](https://gist.github.com/012cbf7148393a026f76e8a5ea3b8956)
[Workspace 1 Programs](https://gist.github.com/889eb94c551d4b32c88380196ccd82f3)

 - Linux distribution: *Disco Dingo*
 - i3-resurrect version (output of `i3-resurrect --version`): *i3-resurrect, version 1.4.0*
 - i3 version (output of `i3 -v`): i3 version 4.17.1
 - Python version (output of `python -V`): *Python 2.7.16* and *Python 3.7.3*

**Comment by JonnyHaystack** [comment]
Hm, what command did you use for the restoration?

Also are you able to run xprop and click on the invisible container(s) and show me what output you get?

**Comment by sabrehagen** [comment]
> Hm, what command did you use for the restoration?

I use [this command](https://github.com/sabrehagen/dotfiles-i3/blob/master/.config/i3/restore-layout.sh#L10).


> Is this a new problem or does it happen in 1.3.2 as well?

No, I downgraded to 1.3.2 and restore works as expected.

> If the layouts were created by version 1.3.2 you'll have to recreate them due to changes to the structure of the layout files (so that the workspace root container's layout mode can be restored correctly).

No, I removed the layout files and recreated them using 1.4.0.

> Also are you able to run xprop and click on the invisible container(s) and show me what output you get?

Unfortunately after upgrading back to 1.4.0 I can't reproduce the issue immediately. I'll report back when I do.

**Comment by JonnyHaystack** [comment]
So was this two issues or just one? Because the issue title doesn't sound like what you are mostly talking about here

**Comment by sabrehagen** [comment]
Just one i.e. that on restoring a session with two windows a total of five windows were created, three of which were blank/empty. Since posting this issue I've learned of `i3-msg open`. Running `i3-msg open` produces the same result as the reported bug. Is it used as part of session restore ever?

**Comment by JonnyHaystack** [comment]
Ah, thanks for clarifying.

I hadn't even heard of `i3-msg open` until now. Seems to be a testing tool used to create an empty container https://www.reddit.com/r/i3wm/comments/775c2t/blankempty_container/doj6zzy?utm_medium=android_app&utm_source=share

I'm certainly not using it anywhere in i3-resurrect. I have somewhat rarely come across your issue where you end up with invisible containers, but I don't know exactly why it happens.

**Comment by sabrehagen** [comment]
No longer encountering this issue.
