### ISSUE TITLE
google-chrome --app mode resurrection

### ISSUE THREAD

**Issue by sabrehagen** [JonnyHaystack/i3-resurrect#73]
**Description**
Windows started with `google-chrome --app=https://yourdomain.com` do not resurrect to the same state as when they were saved.

**Describe the solution you'd like**
R&D: Investivate google-chrome instances started in `--app` mode for unique properties that can be used to restore the window in `--app` mode.

**Additional context**
JSON for `google-chrome --app=...` instance:

```json
[
  {
    "command": [
      "/usr/bin/google-chrome"
    ],
    "working_directory": "/home/jackson"
  }
]
```

![screenshot (2)](https://user-images.githubusercontent.com/1094600/69495626-117b8f80-0f1d-11ea-9cfd-b8e42818667c.png)

**Comment by JonnyHaystack** [comment]
Hi, are you running the latest release or are you running the latest version from the master branch? There's been a bug fix since the last release which should fix your particular issue, which is explained here https://github.com/JonnyHaystack/i3-resurrect/issues/55#issuecomment-555658251.

Unfortunately if you open multiple chrome windows in app mode, they will all have the same cmdline set because of some weirdness in how they set the process cmdline. You can work around that in the way I describe here https://github.com/JonnyHaystack/i3-resurrect/issues/55#issuecomment-555697848.

Seeing as there's been no new bugs reported since the last release, I'll do a release now.

**Comment by sabrehagen** [comment]
I wasn't running the latest at the time of posting, but now I am on `1.4.2`. Still no `--app` flag saved in the config.

```json
{
  "border": "pixel",
  "current_border_width": -1,
  "floating": "auto_off",
  "fullscreen_mode": 1,
  "geometry": {
    "x": 0,
    "y": 0,
    "width": 0,
    "height": 0
  },
  "layout": "splith",
  "name": "4: \uf268",
  "orientation": "horizontal",
  "percent": null,
  "scratchpad_state": "none",
  "sticky": false,
  "type": "workspace",
  "workspace_layout": "default",
  "nodes": [
    {
      "border": "pixel",
      "current_border_width": 2,
      "floating": "auto_off",
      "fullscreen_mode": 0,
      "geometry": {
        "x": 0,
        "y": 0,
        "width": 1919,
        "height": 1079
      },
      "layout": "splith",
      "name": "https://jackson.my-website.com",
      "orientation": "none",
      "percent": 1.0,
      "scratchpad_state": "none",
      "sticky": false,
      "type": "con",
      "workspace_layout": "default",
      "swallows": [
        {
          "class": "^Google\\-chrome$",
          "instance": "^desktop\\.my-website\\.com$"
        }
      ]
    }
  ]
}
```
```json
[
  {
    "command": [
      "/opt/google/chrome/chrome"
    ],
    "working_directory": "/home/jackson"
  }
]
```

**Comment by JonnyHaystack** [comment]
Can you try using `xprop _NET_WM_PID` to get the PID of the chrome process (in app mode) and then show me the output of `hexdump -C /proc/<pid>/cmdline`

**Comment by JonnyHaystack** [comment]
Were you able to get this information?

**Comment by sabrehagen** [comment]
Apologies for the delay. The result when starting `google-chrome --app=https://my-website.com` is:

```sh
> xprop _NET_WM_PID
_NET_WM_PID(CARDINAL) = 877

> ps -p 877 -o args
COMMAND
/opt/google/chrome/chrome

> hexdump -C /proc/877/cmdline
00000000  2f 6f 70 74 2f 67 6f 6f  67 6c 65 2f 63 68 72 6f  |/opt/google/chro|
00000010  6d 65 2f 63 68 72 6f 6d  65 00                    |me/chrome.|
0000001a
```

**Comment by JonnyHaystack** [comment]
Yeah looks similar to the problem eater was having. Different chrome builds seem to be quite inconsistent with how they store the cmdline, and most of them aren't very friendly with it. There's no other way for i3-resurrect to get the arguments that were passed unless you create a custom mapping as I describe here https://github.com/JonnyHaystack/i3-resurrect/issues/55#issuecomment-555697848

That way you just have to create the mapping once for each site that you want to use in app mode, and you won't have to edit the layout files manually.
