### ISSUE TITLE
Crashes due to failed dependancy

### ISSUE THREAD

**Issue by totalolage** [JonnyHaystack/i3-resurrect#74]
The script crashed on launch due to `pkg_resources.DistributionNotFound: The 'enum-compat' distribution was not found and is required by i3ipc`

**To Reproduce**
1. run latest `i3-resurrect`

**Screenshots**
[img](https://i.imgur.com/UuFIbRK.png)

**System information (please complete the following information):**
 - Linux distribution: 5.3.13-arch1-1
 - i3-resurrect version (output of `i3-resurrect --version`):
`Traceback (most recent call last):
  File "/usr/bin/i3-resurrect", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'enum-compat' distribution was not found and is required by i3ipc`
 - i3 version (output of `i3 -v`): i3 version 4.17.1 (2019-08-30)
 - Python version (output of `python -V`): Python 3.8.0

**Comment by JonnyHaystack** [comment]
How did you install i3-resurrect? Everything installs fine and runs without errors on the Travis CI build (Ubuntu Disco), and I'm not having any issues on Arch either. Both AUR packages have `python-enum-compat` from the AUR as a dependency so it should be installed on your system if you installed i3-resurrect via the AUR. Can you verify that you have that package installed?

**Comment by totalolage** [comment]
Yes, the first thing I did was to reinstall `i3-resurrect`, verify that `python-enum-compat` is installed as a dependency, tried installing `python-enum-compa` manually, tried using `i3-resurrect-git` all with same result.

**Comment by JonnyHaystack** [comment]
Okay I have managed to reproduce this. I had enum-compat installed under `~/.local` so that's why it worked. Not sure why it's not working with the python-enum-compat package from the AUR, but I'll look into it.

For now it should work if you do `python3 -m pip install --user enum-compat`

**Comment by JonnyHaystack** [comment]
Looks like something weird is going on with python-enum-compat but I'm not entirely sure what. i3ipc-python has [removed the enum-compat dependency](https://github.com/altdesktop/i3ipc-python/commit/4cc59d5550eab1eb3f0679461fd9c86449b407bc), but this change is not in a release of i3ipc-python.

I'll remove the dependency on python-enum-compat and I'll change the dependency on python-i3ipc to i3ipc-python-git and that should fix it.

**Comment by JonnyHaystack** [comment]
Okay I've updated both AUR packages and it's fixed for me. Let me know if that works for you.

**Comment by totalolage** [comment]
Installing the pip package manually, as well as now with the changed dependancies works. Thanks!
