### ISSUE TITLE
Probelm with workspaces with names starting with space

### ISSUE THREAD

**Issue by ashish-yadav11** [JonnyHaystack/i3-resurrect#75]
change
`i3.command(f'workspace --no-auto-back-and-forth {workspace_name}')`
to
`i3.command(f'workspace --no-auto-back-and-forth "{workspace_name}"')`
on line 113 of i3_resurrect/main.py
The prior takes to workspace "1: terminal" instead of " 1: terminal" even when workspace_name is " 1: terminal".

**Comment by JonnyHaystack** [comment]
Thanks, I'll get this fixed
