### ISSUE TITLE
Programs having names consisting comma do not launch while restoring

### ISSUE THREAD

**Issue by ashish-yadav11** [JonnyHaystack/i3-resurrect#77]
Okular open with file having name starting with comma doesn't launch while restoring.

Steps to reproduce the behavior;
1. run okular -- "file name having comma in it"
2. save the workspace having the okular window
3. restore it
4. okular will not launch

**Expected behavior**
okular should launch

**System information (please complete the following information):**
 - Linux distribution: Arch
 - i3-resurrect version (output of `i3-resurrect --version`): 1.4.2
 - i3 version (output of `i3 -v`): 4.18
 - Python version (output of `python -V`): 3.8.1

**Comment by ashish-yadav11** [comment]
The problem is in line 100, i.e., "        i3.command(f'exec cd "{working_directory}" && {command}')" of i3_resurrect/programs.py

**Comment by ashish-yadav11** [comment]
Why don't you use os.system instead of i3.command. It solves the issue

**Comment by ashish-yadav11** [comment]
My current workaround is to replace line 100 with `os.system(f'cd "{working_directory}" && {command} &')`.

**Comment by ashish-yadav11** [comment]
One question out of the context; can't python-i3ipc in the official repo in arch be used instead of i3ipc-python-git in aur?

**Comment by JonnyHaystack** [comment]
> My current workaround is to replace line 100 with `os.system(f'cd "{working_directory}" && {command} & disown')`.

See #40 for why I use i3's exec command



> One question out of the context; can't python-i3ipc in the official repo in arch be used instead of i3ipc-python-git in aur?

See #72 and #74

**Comment by ashish-yadav11** [comment]
The following resolves the issue too -
replace `cmdline = [f'"{arg}"' for arg in cmdline if arg != '']` on line 94 in programs.py with `cmdline = [f'\\"{arg}\\"' for arg in cmdline if arg != '']` and `i3.command(f'exec cd "{working_directory}" && {command}')` on line 100 with `i3.command(f'exec "cd \\"{working_directory}\\" && {command}"')`.

**Comment by JonnyHaystack** [comment]
Ok thanks! I'll look into that

**Comment by JonnyHaystack** [comment]
> The following resolves the issue too -
> replace `cmdline = [f'"{arg}"' for arg in cmdline if arg != '']` on line 94 in programs.py with `cmdline = [f'\\"{arg}\\"' for arg in cmdline if arg != '']` and `i3.command(f'exec cd "{working_directory}" && {command}')` on line 100 with `i3.command(f'exec "cd \\"{working_directory}\\" && {command}"')`.
> See [i3/i3#2122](https://github.com/i3/i3/issues/2122).

So does this actually work if the command has a comma in it or does it only fix the case where there's a comma in the working directory path?
