### ISSUE TITLE
Restoring a workspace with programs assigned to a another workspace.

### ISSUE THREAD

**Issue by ashish-yadav11** [JonnyHaystack/i3-resurrect#78]
When restoring a workspace (not workspace 8) with more than 1 okular windows (okular is assigned to workspace 8), every once in a while one of the windows opens in workspace 8.

1. Assign okular to workspace 8
2. Go to workspace 1
3. Open 3 okular windows in workspace 1 (They will open in workspace 8, move them to workspace 1)
4. Save the workspace
5. Close all windows in workspace 1
6. Restore workspace 1
7. Every once in a while you will observe that some of the okular windows opened workspace 8.

**Expected behavior**
Every okular window should open in workspace 1

**System information (please complete the following information):**
 - Linux distribution: Arch
 - i3-resurrect version (output of `i3-resurrect --version`): 1.4.2
 - i3 version (output of `i3 -v`): 4.18
 - Python version (output of `python -V`): 3.8.1

**Comment by JonnyHaystack** [comment]
I don't really see how this is something i3-resurrect should have to deal with. Just don't have conflicting rules would be my advice. Personally I used to use assignment rules like that but with i3-resurrect I don't feel the need for them.

I actually have made a dmenu/rofi script that significantly improves the utility of i3-resurrect, but I haven't yet decided how to release it. I'll just drop it here for now so you can have a play with it
```
#!/usr/bin/env bash

ACTIONS=("Restore" "Save" "Delete")
TARGETS=("Programs" "Layout" "Both")
DMENU="dmenu -i"

prompt="i3-resurrect"
action=$(printf "%s\n" ${ACTIONS[@]} | $DMENU -p $prompt)

case $action in
  Save)
    command="i3-resurrect save --swallow=class,instance,title -p"
    ;;
  Restore)
    command="i3-resurrect restore -p"
    ;;
  Delete)
    command="i3-resurrect rm -p"
    ;;
  *)
    echo "Invalid action"
    exit 1
    ;;
esac

prompt="Profile"
profile=$(i3-resurrect ls profiles | awk '{$NF=""; $1=""; print $0}' | uniq | $DMENU -p "$prompt" | xargs)

if [[ "$profile" == "" ]]; then
  echo "Invalid profile"
  exit 1
fi

prompt="Target"
target=$(printf "%s\n" ${TARGETS[@]} | $DMENU -p $prompt)

case $target in
  Programs)
    target_option="--programs-only"
    ;;
  Layout)
    target_option="--layout-only"
    ;;
  Both)
    target_option=""
    ;;
  *)
    echo "Invalid target"
    exit 1
    ;;
esac

if [[ -n "$target_option" ]]; then
  $command "$profile" "$target_option"
else
  $command "$profile"
fi
```
