### ISSUE TITLE
Can't use the command "i3-resurrect save -w (num)"

### ISSUE THREAD

**Issue by Zxrcoming** [JonnyHaystack/i3-resurrect#8]
when I installed the i3-resurrect, and type the "i3-resurrect save -w .." in my gnome-ternimal.
it shows that "command not found.."
i don't have problem with installing.
I was wondering WHY?

**Comment by JonnyHaystack** [comment]
Which install method did you use?

**Comment by JonnyHaystack** [comment]
Hm I seem to have this problem too when installing with pip. I don't remember changing anything in the setup.py so that's strange. I'll take a look.

**Comment by JonnyHaystack** [comment]
Oh hang on, you probably just don't have ~/.local/bin in your PATH.
Try `export PATH=$PATH:~/.local/bin` and then run i3-resurrect again.

Let me know if that fixes it. I should probably add that to the README.

**Comment by Zxrcoming** [comment]
yeah,it's the path issus,I now can use the command after I added the path.
thank you for response.
Appreciate.

**Comment by JonnyHaystack** [comment]
Glad to know it's working now :smile:
