### ISSUE TITLE
Saving and restoring AppImage windows fail

### ISSUE THREAD

**Issue by Kabouik** [JonnyHaystack/i3-resurrect#82]
**Describe the bug**
Saving a workspace containing AppImage windows works, but their launch command is not correct and therefore restoring will fail.

**To Reproduce**
1. Launch some AppImage applications (using Rofi drun modi for instance)
2. Save workspace with i3-resurrect
3. Close everything
4. Try restoring workspace with i3-resurrect

**Expected behavior**
Save the correct launch commands for AppImage applications (not sure how to do that; they are in the .desltop files but I don't think i3-resurrect parses those files to get the launch commands).

**Screenshots**
![ss-2020-03-08_034132](https://user-images.githubusercontent.com/7107523/76155654-b5f99a00-60e6-11ea-8fa1-3357adfbdb5d.png)

Note the profile_programs.json on the top left: Molotov and mattermost-desktop both are AppImage applications.

**System information (please complete the following information):**
 - Linux distribution: Solus
 - i3-resurrect version (output of `i3-resurrect --version`): version 1.4.2
 - i3 version (output of `i3 -v`): 4.17.1 (2019-08-30)
 - Python version (output of `python -V`): Python 2.7.17 (weird, I don't understand why it defaults to the old Python; I have Python 3 installedtoo)

**Comment by JonnyHaystack** [comment]
In cases like these your best bet is probably creating window command mappings in the i3-resurrect config file (see README)

**Comment by JonnyHaystack** [comment]
In case you had trouble creating the mappings, it would be something like this in your i3-resurrect config:
```
{
  "window_command_mappings": [
    {
      "class": "Molotov",
      "command": "/path/to/molotov.AppImage"
    }
  ]
}
```
