### ISSUE TITLE
Question: Does it work with multiple monitors?

### ISSUE THREAD

**Issue by MikaelElkiaer** [JonnyHaystack/i3-resurrect#83]
Not much to add besides the headline.
I've searched through the readme and all other issues, but found nothing, so I thought I might as well go ahead and ask. :)

**Comment by JonnyHaystack** [comment]
Hi

As workspaces in i3 are only attached to a single monitor, it doesn't matter whether you are using one monitor or 5 :)

I personally use a dual monitor setup, if that's any extra comfort.

**Comment by MikaelElkiaer** [comment]
Thanks for the answer.
I'll definitely check this out soon. :)
