### ISSUE TITLE
The dependency i3ipc-python-git is probably not maintained any more

### ISSUE THREAD

**Issue by ashish-yadav11** [JonnyHaystack/i3-resurrect#85]
The dependency i3ipc-python-git in aur has not been updated since July 2019 while new versions of i3ipc-python has been released and the package in official repo has been updated.
You might want to change the dependency to the version in official repo.

**Comment by JonnyHaystack** [comment]
Thanks for the heads up. Yes it looks like this would be a good time to switch back to the official package. If anyone on manjaro has any problems again, they have many other ways to install that dependency anyway.

**Comment by JonnyHaystack** [comment]
It has been done :tada:
