### ISSUE TITLE
Is it possible to set the directory using the configuratoin

### ISSUE THREAD

**Issue by EugenMayer** [JonnyHaystack/i3-resurrect#90]
I checked the documentation, and mostly the settings are around mapping titles/commands/terminals.

I would like to relocate the workspace-folder using the configuration, so i do not need to set it in every command. Is this possible?

**Comment by JonnyHaystack** [comment]
That's on my list of things to do. No one had requested it until now so I hadn't made it a priority, but seeing as you've asked now I will try to get on that.
