### ISSUE TITLE
Broken saving with -w and -p flag together 

### ISSUE THREAD

**Issue by eater** [JonnyHaystack/i3-resurrect#97]
**Describe the bug**
When I try to save a specific workspace to a specific profile, the saved json is empty. 

**To Reproduce**
1. `i3-resurrect save -w 1 -p desk`
2. Observe that profiles/desk_layout.json and profiles/desk_programs.json have been created but they are both 2-byte `[]` files.
3. With one flag at a time, `i3-resurrect save -w 1` works great and so does `i3-resurrect save -p desk`

**Expected behavior**
The workspace specified with the `-w` flag should be saved to the profile specified with the `-p` flag. 

**System information (please complete the following information):**
 - Linux distribution: Ubuntu 18.04
 - i3-resurrect version (output of `i3-resurrect --version`): Running version 1.4.3. 
 - i3 version (output of `i3 -v`): 4.19
 - Python version (output of `python -V`): 3.6.9

**Comment by JonnyHaystack** [comment]
Thanks for the report, I hadn't realised that wasn't working. Will look into it later.

**Comment by JonnyHaystack** [comment]
Hmm, can't reproduce this... And based on what you said in #98 it seems like this *is* working for you. Can you confirm if you're still having this problem, and if so can you specifically identify anything that is causing this to sometimes not work?

**Comment by eater** [comment]
Hmmm, good point. I think I was forgetting the `-n` flag when I was saving specific workspaces to specific profiles. I am able to get it to work now as long as I remember that!
